Comprehensive encoding/decoding tests
qt4cg/qt4tests pull request #64
Opened 2023-10-26 09:51 UTC by ndw

This PR adds a comprehensive set of tests for encoding and decoding characters in URIs. All of the characters from space (`%20`) to ~ (`%7E`) and a range of higher Unicode characters and emoji are included. This should assure that implementations get consistent results for both parsing URIs (and decoding the parts of the URI) and building URIs (and encoding the parts of the URI).

The test results are (to the best of my knowledge at the moment) correct and consistent with both `fn:decode-for-uri` and the notes in https://github.com/qt4cg/qtspecs/issues/774

(I hope I've encoded the tests so that they work with the XQuery driver; apologies if I messed up anywhere. I'd be very interested in hearing what differences, if any, other implementations give.)

2023-10-26 13:00 UTC, ChristianGruen requested changes
For the tests we look at, it may be easier to always use backticks instead of classical quote characters.

2023-10-26 13:20 UTC, ndw commented on fn/build-uri.xml
> +      <assert-eq>"http://example.com/%20!%22%23$%25&amp;'()*+,-.%2F0123456789:;%3C=%3E%3F?a=%20!%22%23$%25%26'()*+,-&amp;b=./0123456789:;%3C%3D%3E?#%20!%22%23$%25&amp;'()*+,-./0123456789:;%3C=%3E?"</
I'm testing out the rules described in https://github.com/qt4cg/qtspecs/issues/774

2023-10-26 13:34 UTC, ChristianGruen commented
Should be ok now (there are other failing cases, like `fn-build-uri-009`, but they aren’t part of this commit anyway).

2023-10-30 16:06 UTC, ChristianGruen commented
I’ll merge this one. Maybe I can revise some minor bugs in the remaining tests by myself.

2023-10-30 16:06 UTC, merged